version: '2'

services:

  jenkins:
    image: ychernenko/jenkins
    build: ./context
    volumes:
      - ~/docker-volumes/jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
